// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analytics.proto

/*
Package analytics is a generated protocol buffer package.

It is generated from these files:
	analytics.proto

It has these top-level messages:
	AdditionAnalytics
*/
package analytics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdditionAnalytics struct {
	Numbers []int32 `protobuf:"varint,1,rep,packed,name=numbers" json:"numbers,omitempty"`
	Time    int64   `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
}

func (m *AdditionAnalytics) Reset()                    { *m = AdditionAnalytics{} }
func (m *AdditionAnalytics) String() string            { return proto.CompactTextString(m) }
func (*AdditionAnalytics) ProtoMessage()               {}
func (*AdditionAnalytics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AdditionAnalytics) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *AdditionAnalytics) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*AdditionAnalytics)(nil), "analytics.AdditionAnalytics")
}

func init() { proto.RegisterFile("analytics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcc, 0x4b, 0xcc,
	0xa9, 0x2c, 0xc9, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x39, 0x72, 0x09, 0x3a, 0xa6, 0xa4, 0x64, 0x96, 0x64, 0xe6, 0xe7, 0x39, 0xc2, 0x04, 0x85, 0x24,
	0xb8, 0xd8, 0xf3, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x58, 0x83,
	0x60, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6,
	0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x36, 0xb5,
	0x55, 0x67, 0x00, 0x00, 0x00,
}
